# Generated by Django 4.1 on 2023-09-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fakenews_model",
            old_name="title",
            new_name="Newstitle",
        ),
    ]
