# Generated by Django 4.1 on 2023-09-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_title_fakenews_model_newstitle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fakenews_model",
            old_name="Newstitle",
            new_name="title",
        ),
    ]
