# Generated by Django 4.1 on 2023-09-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_newstitle_fakenews_model_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fakenews_model",
            name="date",
            field=models.DateField(),
        ),
    ]
